(function (root, factory) {
  const content = typeof module === 'object' && module.exports ? require('./content.js') : root.AtlasContent;
  const scenarios = typeof module === 'object' && module.exports ? require('./scenarios.js') : root.AtlasScenarios;
  const questions = factory(content, scenarios);
  if (typeof module === 'object' && module.exports) module.exports = questions;
  else root.AtlasQuestions = questions;
})(globalThis, function (content, scenarios) {
  'use strict';
  const bank = [];
  function add(lessonId, scenario, rows, overrides = {}) {
    const lesson = content.lessons.find((item) => item.id === lessonId);
    for (const [stem, options, correct, rationale] of rows) {
      const answers = Array.isArray(correct) ? correct : [correct];
      bank.push({ id: `atlas-${bank.length + 1}`, lesson: lessonId, scenario, domains: { ...lesson.domains, ...overrides }, stem, options, correct: answers, kind: answers.length > 1 ? 'multiple' : 'single', rationale, source: 'Atlas original practice' });
    }
  }

  add('first-principles', 'Foundations', [
    ['A teammate trusts a polished answer about an internal system that was never described to Claude. What is the best next step?', ['Use it because the instructions are detailed.', 'Check it against internal documentation or an authorized source.', 'Ask for the same answer in a table.', 'Lower temperature to prove it correct.'], 1, 'The model was not given the private facts. Independent evidence is needed; confidence, formatting, and sampling settings cannot establish correctness.'],
    ['An API prototype behaves differently from the same question in claude.ai. What should you compare first?', ['Only the spelling of the user request.', 'Whether the API is inherently less capable.', 'Model version, system instructions, tools, and supplied context.', 'Whether the developer has used the product long enough.'], 2, 'The surrounding product changes the effective input and capabilities. Reproduce the relevant conditions and evaluate before blaming the model surface.'],
  ]);
  add('prompt-brief', 'Prompt workshop', [
    ['A supplier analysis only repeats the spreadsheet. Which brief most directly improves usefulness?', ['Analyze harder.', 'Act as the best analyst in the world.', 'Make the answer longer.', 'Rank suppliers by delivery risk and cost for next quarter, citing the supplied data.'], 3, 'The last brief provides decision criteria and evidence. Persona, emphasis, and length do not specify what useful analysis means.'],
    ['The report has the right facts but inconsistent headings. Which prompting addition is most useful?', ['A few examples using the exact required headings and section order.', 'More randomly selected source documents.', 'A warning in capital letters.', 'A higher temperature.'], 0, 'Examples demonstrate the intended shape. They improve consistency but do not eliminate the need for output validation.'],
    ['Choose TWO useful elements of a customer announcement brief.', ['The intended audience and purpose.', 'An instruction to guess the missing release facts.', 'The required length, tone, and call to action.', 'A demand for perfect accuracy without source material.', 'The same vague request repeated several times.'], [0, 2], 'Audience and deliverable constraints give the model actionable direction. Missing release facts still need evidence or explicit uncertainty.'],
    ['A draft buries the action the reader must take. What is the best revision request?', ['Try again.', 'Move the requested action into the first two sentences and shorten background to one paragraph.', 'Forget all constraints.', 'Make it more impressive.'], 1, 'Targeted feedback identifies the defect and the desired change. Vague regeneration spends another attempt without reducing ambiguity.'],
  ]);
  add('verify-output', 'Everyday work', [
    ['A board briefing cites a precise market statistic. What makes it publishable?', ['It appears in two generated answers.', 'The model says it is 98% confident.', 'It is checked against the actual authoritative source and its context.', 'It has a professional-looking citation.'], 2, 'Independent verification checks both the number and what it measures. Generated agreement and citation appearance can repeat an error.'],
    ['How do you check a summary for completeness?', ['Compare its coverage with material sections and provisions in the source.', 'Count only its words.', 'Confirm it has a conclusion.', 'Ask the summarizer whether anything was omitted.'], 0, 'Important omissions are discovered by comparing with the source. Length and self-confirmation are not coverage checks.'],
    ['A table and narrative contradict each other. What should you do?', ['Trust the table automatically.', 'Trust the prose automatically.', 'Average the conflicting claims.', 'Check both against the source and correct the inconsistency.'], 3, 'Either representation can be wrong. Resolve the contradiction with evidence instead of privileging a format.'],
    ['Choose TWO outputs needing especially careful independent verification.', ['A specific quotation attributed to a person.', 'A nicely formatted heading.', 'A friendly greeting.', 'A material claim about a very recent regulation.', 'A short paragraph rather than a long one.'], [0, 3], 'Attribution and recent specialized facts carry meaningful correctness risk. Presentation is not a reliable indicator either way.'],
    ['Two apology drafts are both grammatical. How should the author choose?', ['Use whichever is longer.', 'Compare both against acknowledgment, responsibility, remedy, and brand-voice criteria.', 'Let the model choose without human review.', 'Merge both complete texts.'], 1, 'A rubric makes the comparison meaningful. The responsible author still owns the sensitive communication.'],
  ]);
  add('projects', 'Everyday work', [
    ['A team repeats the same monthly task with the same documents and rubric. What fits best?', ['A fresh generic chat every month.', 'A Project with curated knowledge and standing instructions.', 'A larger output budget.', 'An instruction to permanently learn the files through repetition.'], 1, 'A Project reduces repeated setup. Its stored context is not model fine-tuning and still needs maintenance.'],
    ['You need many revisions of a reusable proposal. Which format fits?', ['A separate chat for every paragraph.', 'A new untracked copy on each turn.', 'An artifact or maintained document with reviewed revisions.', 'A one-line inline response.'], 2, 'A maintained work product supports revision and sharing. Fragmenting versions across conversations loses continuity.'],
    ['A market briefing needs current sources from many sites. What is the suitable starting capability?', ['Research/search with cited sources, followed by verification.', 'A plain answer from training knowledge alone.', 'Last year\'s report with guessed updates.', 'The largest context window without sources.'], 0, 'Current research needs current evidence. A research feature helps gather it, but citations still need checking.'],
    ['What does a Project NOT guarantee?', ['A place for reference material.', 'Shared instructions for recurring work.', 'Less repeated setup.', 'Unlimited context and perfectly accurate recall.'], 3, 'Projects organize reusable context. They do not abolish context limits or guarantee factual correctness.'],
  ]);
  add('knowledge', 'Knowledge workspace', [
    ['A quoting assistant keeps using last year\'s prices. What is the best fix?', ['Repeat "ignore old prices" in every chat.', 'Increase output tokens.', 'Replace or exclude obsolete sources from current quoting and establish a review cycle.', 'Keep both versions unlabeled and let Claude choose.'], 2, 'Fix the source of stale answers. Old versions may be retained for audit, but current-answer retrieval must distinguish them.'],
    ['Which configuration separates behavior and evidence correctly?', ['Tone rules in instructions; current product catalog in knowledge.', 'Catalog in instructions; all rules only in reference files.', 'Both only in a private chat from last month.', 'No configuration because the model learns the team automatically.'], 0, 'Instructions express standing behavior; knowledge supplies reference facts. Correct placement makes recurring work more consistent.'],
    ['Only 18 of 2,000 files are relevant to a proposal workflow. What should the initial knowledge set contain?', ['Every file so nothing can be missing.', 'Only the oldest files.', 'No reference material.', 'The relevant current files with identifiable sources and owners.'], 3, 'Curated relevant evidence reduces noise and stale conflicts. Add other sources when the task actually needs them.'],
    ['What comes before connecting live company documents?', ['Testing with confidential records first.', 'Checking approved use, permissions, sensitivity, and freshness behavior.', 'Sharing one administrator account.', 'Disabling document updates.'], 1, 'Live access is a governance decision as well as a convenience. A connector does not waive existing data policy.'],
    ['What is the right setup order?', ['Test an empty Project, then decide its purpose.', 'Refine before seeing an output.', 'Create, configure instructions, add curated references, test, then refine.', 'Upload everything and skip testing.'], 2, 'Configuration precedes a meaningful test; the test then provides evidence for refinement.'],
    ['A team keeps pasting the same tone and report rules. Where should those go?', ['The Project\'s standing instructions.', 'A different private chat per user.', 'Only in the finished report.', 'In a screenshot the model never receives.'], 0, 'Reusable behavioral configuration removes repeated overhead and onboarding drift. It remains guidance, not a perfect compliance guarantee.'],
    ['A verified planning decision is needed next month. What preserves it reliably?', ['Assume every new conversation remembers it.', 'Keep a browser tab open indefinitely.', 'Recreate it from memory.', 'Save a verified decision summary in an approved durable location.'], 3, 'Deliberate storage preserves the outcome beyond a session. Reopening a tab or assuming recall is not a controlled recordkeeping process.'],
  ]);
  add('workflow-choice', 'Architecture desk', [
    ['Every document follows extract, validate, and archive, with a check at each stage. Which design is the strongest starting point?', ['A fully autonomous team of agents.', 'A fixed workflow with explicit stage contracts.', 'One unlimited prompt.', 'A random choice of pipelines.'], 1, 'Known steps and intermediate checks favor code-controlled sequencing. Autonomy adds overhead without a requirement for dynamic planning.'],
    ['Most invoices follow a stable process; unusual formats require investigation or human routing. Which design fits?', ['An agent for every operation regardless of format.', 'A separate agent for every field.', 'A workflow for the normal path with bounded agentic handling at the exception point.', 'A prompt that hopes all formats look the same.'], 2, 'A hybrid localizes autonomy to the uncertainty. It preserves predictable processing where it already works.'],
    ['An investigation\'s next diagnostic query depends on each new finding. Which pattern fits?', ['A bounded autonomous plan-act-observe loop.', 'A fixed list of all possible queries.', 'One translation-style call.', 'A random batch of diagnoses.'], 0, 'The path is discovered during execution. A bounded agent can adapt, while an exhaustive fixed script cannot anticipate every branch efficiently.'],
  ]);
  add('decomposition', 'Architecture desk', [
    ['A single prompt skips policies in a large compliance review despite clearer wording. What is the next structural improvement?', ['Repeat the prompt twice.', 'Only lower temperature.', 'Hide the missing sections.', 'Extract, assess policy groups, validate, score, then synthesize.'], 3, 'Focused intermediate steps address overloaded attention and enable coverage checks. Sampling changes do not create that structure.'],
    ['A customer raises a refund, an address issue, and missing credits. How should the system organize the work?', ['Resolve the first issue only.', 'Track each issue, share verified facts, investigate independent parts, then return a unified resolution.', 'Require three new tickets immediately.', 'Escalate every multi-issue request automatically.'], 1, 'Explicit decomposition preserves coverage and reduces duplicated context. Dependent writes still need ordering and authorization.'],
    ['Which order produces a trustworthy board summary?', ['Draft, set the audience, then perhaps verify.', 'Extract everything before deciding the goal.', 'Define purpose, extract relevant findings, verify them, draft, then refine.', 'Polish the source and skip checking.'], 2, 'Purpose directs extraction; verification comes before downstream dependence. Polishing unverified facts can make mistakes more persuasive.'],
    ['How should brainstorming differ from a formal charter?', ['Explore varied options for brainstorming; give structure and constraints for the charter.', 'Use identical vague instructions.', 'Constrain every brainstorm to one answer and leave the charter unstructured.', 'Avoid both because they cannot be verified.'], 0, 'The prompt should match the divergent or convergent nature of the task. Required structure matters much more for a formal deliverable.'],
  ]);
  add('agent-loop', 'Customer support', [
    ['A raw Messages API response contains text and stop_reason: tool_use. What next?', ['Treat the text as the final answer.', 'Execute authorized requested tools, append assistant and matching tool results, then call the model again.', 'Stop after five calls regardless of state.', 'Search the text for the word complete.'], 1, 'The structured stop reason drives control flow. Prose may coexist with requested tool use and is not a termination signal.'],
    ['How does a raw Messages API call learn what a client tool returned?', ['The tool changes model weights.', 'The tool description changes automatically.', 'The runtime includes a tool_result referencing the tool_use_id in subsequent message history.', 'The API can read any local process\'s memory.'], 2, 'Client code returns results through the conversation protocol. The model cannot see local execution without that data.'],
    ['An agent stops because it hits max_turns. What should the application report internally?', ['A bounded run that may be incomplete, identified by its structured result.', 'Guaranteed success.', 'A longer response than expected.', 'A new training session.'], 0, 'A resource bound is a backstop, not evidence the task is done. Preserve partial state and handle the result intentionally.'],
  ]);
  add('sdk-boundary', 'Application integration', [
    ['Your team explicitly chooses the Agent SDK. Who should normally handle its loop and tool dispatch?', ['The model writes plaintext commands and the app guesses.', 'A second duplicate custom loop.', 'A spreadsheet of tool states.', 'The SDK runtime, configured with your tools and policy controls.'], 3, 'The Agent SDK supplies the harness. Your application still owns authorization, validation, and outcomes; duplicating the loop defeats the selected abstraction.'],
    ['What does an official API client SDK mainly add over hand-written HTTP?', ['Lower token prices.', 'Typed request/response handling, auth plumbing, retry/error helpers, and streaming parsing.', 'Guaranteed accuracy.', 'Unlimited requests.'], 1, 'Client SDK conveniences reduce integration plumbing. They do not change service pricing, limits, or model correctness.'],
  ]);
  add('coordination', 'Research team', [
    ['All research branches succeed, but every assigned branch covers pricing and none covers regulation. Where is the primary defect?', ['The synthesis model\'s tone.', 'The search service\'s uptime.', 'The coordinator\'s task partitioning and coverage plan.', 'The report\'s word count.'], 2, 'The specialists did the assigned work. The coordinator omitted a required topic before research began.'],
    ['Choose TWO reasons a multi-agent design may be justified.', ['Distinct subproblems need different tools and context.', 'The project budget is large.', 'Stakeholders want a more impressive diagram.', 'Independent specialist work can run in parallel.', 'Multiple agents eliminate uncertainty.'], [0, 3], 'Specialization and independent parallel work can justify coordination cost. Budget and novelty alone are not architectural requirements.'],
    ['A regulated sequence must stop after any failed approval step. What enforces this?', ['Let every specialist run in parallel.', 'Ask the final writer to omit unapproved results.', 'Use peer messages and hope ordering emerges.', 'An orchestrator that sequences, records, and gates each stage.'], 3, 'The required ordering and stop behavior belong in deterministic control flow. A final text edit cannot undo earlier side effects.'],
  ]);
  add('subagent-context', 'Research team', [
    ['A fresh synthesis subagent receives only "combine the findings" and produces generic prose. What is missing?', ['More enthusiasm.', 'The actual findings, evidence, and output requirements in its brief.', 'A larger timestamp.', 'A second coordinator with the same prompt.'], 1, 'An ordinary fresh subagent does not inherit the parent transcript. It needs explicit task data.'],
    ['Which configuration limits a current SDK reviewer to examining files?', ['Only a sentence saying never edit.', 'An allowedTools pre-approval list alone.', 'Its actual tools list restricted to Read, Grep, and Glob.', 'A title containing the word safe.'], 2, 'The actual tool inventory constrains capability. Current allowedTools controls pre-approval, not removal of every other tool.'],
  ]);
  add('hooks', 'Customer support', [
    ['Autonomous refunds must never exceed 500. Prompts occasionally permit 650. What is the root-level control?', ['Validate and block over-cap operations before execution, with backend enforcement and human routing.', 'Repeat the limit more often.', 'Increase the model tier.', 'Audit the refund only after payment.'], 0, 'A pre-execution gate enforces the invariant. Prompts reduce probability; post-action auditing detects rather than prevents the side effect.'],
    ['Third-party tools return inconsistent date formats. Where is deterministic normalization best placed?', ['In the model\'s memory alone.', 'As an optional tool the model may skip.', 'In the final response after decisions are made.', 'In a tool-result adapter or suitable PostToolUse handler before consumption.'], 3, 'Normalize data at the ingestion boundary. The agent then reasons over consistent formats without having to choose the cleanup step.'],
    ['A Claude Code policy hook exits with code 1 and no deny decision. Is that a reliable block?', ['Yes, all nonzero codes block.', 'No; use the documented blocking decision or exit 2, and test failure behavior.', 'Only if the prompt asks nicely.', 'Yes, but only after five retries.'], 1, 'Generic nonzero failures can be non-blocking. Correct output semantics, matching, failure tests, and backend controls matter.'],
  ]);
  add('sessions', 'Code generation', [
    ['Yesterday\'s investigation is valid and you want to continue that named session. What fits?', ['A fresh generic prompt with no summary.', 'Reset every session globally.', 'Resume the specific session.', 'Raise max_tokens to retrieve memory.'], 2, 'Resuming retains relevant conversation context. Increasing response limits does not restore history.'],
    ['The files changed substantially since the old analysis. What is safest?', ['Start with a verified summary and reread current evidence.', 'Trust every old tool result as current.', 'Ignore all previous conclusions permanently.', 'Ask the model to treat old source as new.'], 0, 'Preserve useful conclusions while refreshing stale evidence. Resumption is useful only when its stored facts remain appropriately current.'],
    ['What does forkSession isolate by itself?', ['Every edited file.', 'All external service state.', 'The organization\'s API keys.', 'A new conversation branch from a shared history baseline.'], 3, 'Conversation forking is not filesystem isolation. Parallel editing requires separate worktrees or equivalent isolation.'],
  ]);
  add('tool-descriptions', 'Tool integration', [
    ['Two lookup tools have nearly identical descriptions and are confused. What should change first?', ['Add another routing model.', 'Clarify input formats, outputs, and use-versus-do-not-use boundaries.', 'Alphabetize the tools.', 'Add more overlapping tools.'], 1, 'The descriptions are the most direct ambiguity to fix. More routing machinery can conceal rather than remove the unclear contract.'],
    ['An 18-tool specialist frequently performs another specialist\'s tasks. Which redesign is strongest?', ['A longer warning to ignore the extras.', 'Increase its randomness.', 'Give it a role-relevant inventory and remove unnecessary overlap.', 'Rename every tool tool_1 through tool_18.'], 2, 'Scope actual capabilities. Small purposeful inventories improve clarity; there is no universal hard limit of five tools.'],
  ]);
  add('tool-choice', 'Structured extraction', [
    ['The model must call an extraction tool but may choose among document schemas. Which mode fits?', ['tool_choice: { type: "any" }', 'tool_choice: { type: "auto" }', 'tool_choice: { type: "none" }', 'A forced unrelated tool.'], 0, 'any requires a tool call while leaving tool selection open. Strict schema configuration and validation are separate concerns.'],
    ['What does forcing tool_choice to a named tool NOT guarantee?', ['The selected tool name.', 'A constraint on the next model action.', 'The required choice of tool.', 'Business authorization or factual correctness of its inputs.'], 3, 'Selection is not authority and is not truth. Backend policy and semantic validation remain required.'],
  ]);
  add('tool-errors', 'Tool integration', [
    ['A tool reports both a timeout and an expired return window as "failed". What should it return instead?', ['The same empty object for both.', 'Structured category, retryability, useful message, and relevant context.', 'Success so the agent stays positive.', 'Only a stack trace.'], 1, 'The recovery differs: transient failures may retry, policy refusals do not become allowed by repetition. Structured results make that difference actionable.'],
    ['An MCP tool cannot parse a document. How should its tool result signal failure?', ['Ordinary successful text starting ERROR.', 'A normal empty successful result.', 'isError: true with useful content explaining the failure.', 'A made-up result to preserve the pipeline.'], 2, 'MCP has an explicit tool-error flag. Messages API tool_result uses a different spelling, is_error. Preserve that boundary in the adapter.'],
  ]);
  add('mcp', 'Tool integration', [
    ['Several AI clients need centrally maintained access to the same catalog. What best fits reuse?', ['An MCP server with well-defined operations and access controls.', 'Copy the full catalog into each prompt manually.', 'Teach each model to invent the REST interface.', 'Give every client unrestricted database credentials.'], 0, 'MCP standardizes discovery and invocation while the service remains centrally owned. It does not replace authorization.'],
    ['Which MCP primitive naturally exposes a read-only catalog or schema reference?', ['A forced financial operation.', 'A hidden system instruction.', 'A model weight update.', 'A resource that the host can discover and supply as context.'], 3, 'Resources represent contextual data. They still need a host/client path to reach the model; they are not automatic global memory.'],
    ['A brand checklist needs on-demand loading but no external service. Which extension is simplest?', ['A new MCP server with no operations.', 'A skill containing the procedure and reference material.', 'A secret in every prompt.', 'A new trained model for every edit.'], 1, 'Skills package task knowledge and can reference scripts. An integration server adds little when there is no external capability to expose.'],
  ]);
  add('mcp-config', 'Team configuration', [
    ['Where should a shared Claude Code MCP server definition live?', ['Only in the original developer\'s home directory.', 'In a prose paragraph in CLAUDE.md.', 'In project-root .mcp.json with secret references, not literal tokens.', 'In the app\'s generated build output.'], 2, 'Project scope distributes the connection definition with the repository; each environment supplies its own approved credentials.'],
    ['Which transport pairing is appropriate?', ['stdio for a client-spawned local server; Streamable HTTP for a shared remote service.', 'stdio for remote clients across the internet without a host.', 'No transport because clients read server source.', 'Only legacy SSE for all new local integrations.'], 0, 'Transport follows topology. Streamable HTTP is the modern remote option; legacy SSE is not required for new deployments.'],
  ]);
  add('code-tools', 'Developer productivity', [
    ['Choose TWO correct tool matches.', ['Grep searches only filenames.', 'Glob reads file contents for error messages.', 'Glob finds **/*Test.kt paths.', 'Write is the first step before reading a file.', 'Grep finds occurrences of an error string in contents.'], [2, 4], 'Glob is path matching; Grep is content searching. This distinction saves context and keeps investigation targeted.'],
    ['An edit anchor matches six places. What is a safe next step?', ['Delete five occurrences.', 'Read relevant surrounding context and form a unique edit; carefully rewrite the full file only if necessary.', 'Retry the same ambiguous edit indefinitely.', 'Overwrite the file without reading it.'], 1, 'Increase precision first. A whole-file replacement is a fallback only with complete knowledge and review, not a reason to discard unseen changes.'],
  ]);
  add('instructions', 'Team configuration', [
    ['A new teammate misses conventions that only exist in your ~/.claude/CLAUDE.md. What fixes distribution?', ['Reinstall their CLI.', 'Repeat the rules until the model learns.', 'Commit the shared rules in project-level CLAUDE.md.', 'Give them your entire home directory.'], 2, 'User-scope guidance does not travel with the repository. Project instructions do.'],
    ['Tests are co-located across many directories. Where should conventions be scoped?', ['.claude/rules/ with paths globs matching the tests.', 'Only the first directory\'s README.', 'A manual message in every session.', 'A deployment skill unrelated to tests.'], 0, 'Path-scoped rules handle cross-cutting file patterns without loading every unrelated convention.'],
    ['Does moving a large CLAUDE.md into unconditional @path imports save context?', ['Yes, imports are never read.', 'Yes, filenames replace their contents.', 'Only if the filenames are short.', 'No; imports help organization but their loaded contents still use context.'], 3, 'Use path-specific loading or task skills to avoid irrelevant context. Unconditional imports are organizational, not free storage.'],
  ]);
  add('skills', 'Team configuration', [
    ['A research skill floods the main conversation with exploration. Which setting helps isolate that work?', ['argument-hint alone.', 'context: fork with a self-contained task.', 'A longer title.', 'A higher response limit.'], 1, 'A forked skill runs in an isolated subagent context and returns its result. Unlike conversation forking, it does not inherit the whole chat.'],
    ['Developers omit required skill arguments. What does argument-hint provide?', ['Guaranteed runtime argument validation.', 'A secret input channel.', 'An autocomplete hint; the workflow must still handle missing or invalid arguments.', 'A restriction on filesystem writes.'], 2, 'The hint helps entry but is not validation. Add explicit checks or clarification before side effects.'],
    ['Where does a personal skill variant belong without modifying teammates\' workflow?', ['In ~/.claude/skills/ under a distinct name.', 'Overwriting the committed team skill.', 'In a production secrets file.', 'Inside every source file.'], 0, 'Personal scope and a distinct name avoid accidental shadowing and leave the maintained team workflow available.'],
  ]);
  add('permissions', 'Developer productivity', [
    ['A skill lists only Read under allowed-tools. Is Bash therefore absent?', ['Always.', 'Only if the skill description says so.', 'Only during daylight.', 'No; pre-approval is not an exclusive inventory. Use actual restrictions for a prohibition.'], 3, 'Current documentation separates tool availability from pre-approval. Do not build a security claim on the wrong control.'],
    ['A removal action requires a preview and human approval. Which design is strongest?', ['Let the model set confirmed: true.', 'Validate a single-use approval bound to authenticated user, exact action, and previewed inputs.', 'Allow execution if any preview happened recently.', 'Ask politely for confirmation but execute without checking.'], 1, 'The service must verify that approval actually exists for this exact operation. A model-controlled boolean or an unapproved preview token is insufficient.'],
  ]);
  add('plan-iterate', 'Code generation', [
    ['A migration touches 50 files with several viable service boundaries. What should happen first?', ['Make every edit before discussing scope.', 'Only run a formatter.', 'Investigate, compare approaches, and agree on an implementation plan.', 'Increase temperature to discover a design.'], 2, 'The architectural ambiguity and blast radius justify planning before changes. After agreement, implementation should still be incremental.'],
    ['Choose TWO safeguards for an AI-assisted legacy refactor.', ['Characterization tests of existing behavior.', 'Disable CI to avoid noise.', 'One giant unreviewed patch.', 'Small verified steps using the existing test helpers.', 'Assume AI-generated code needs no review.'], [0, 3], 'Pin behavior first, then keep changes small and validated. That reduces regression risk and makes failures easier to locate.'],
  ]);
  add('ci', 'Continuous integration', [
    ['A CI job waits for interactive input. Which invocation fixes the operating mode?', ['claude --batch', 'CLAUDE_HEADLESS=true only', 'A plain interactive session with no permissions plan', 'claude -p with appropriate permission configuration'], 3, '-p / --print is the documented non-interactive mode. Permission handling and structured output still need deliberate setup.'],
    ['The pipeline needs JSON findings matching a schema. What should it use?', ['Regex over prose.', '--output-format json plus --json-schema, reading and validating structured_output.', 'Only a request to be concise.', 'A screenshot of the response.'], 1, 'The JSON envelope alone is not a findings contract. Schema-shaped structured_output is the application data to inspect.'],
  ]);
  add('review-quality', 'Continuous integration', [
    ['"Only report high-confidence findings" still produces many false positives. What is more effective?', ['Repeat high-confidence three times.', 'Hide the rationale.', 'Define reportable defect categories, exclusions, and examples.', 'Report every suspicion as critical.'], 2, 'Operational criteria communicate a decision boundary. Raw self-confidence cannot replace it.'],
    ['Why review generated code in a fresh independent context?', ['It reduces anchoring to the generator\'s prior rationale.', 'It guarantees every bug is found.', 'It makes tests unnecessary.', 'It removes the need for humans to authorize merging.'], 0, 'Independence improves scrutiny, not certainty. Tests, evidence, and human responsibility remain necessary.'],
    ['A review bot reposts resolved findings after every push. Which fix preserves coverage?', ['Review only once ever.', 'Randomly hide half the comments.', 'Review only the last file alphabetically.', 'Include prior findings and current code, report new or unresolved issues, and update existing comments.'], 3, 'Use prior results as context and make posting idempotent. Reviewing only the newest diff can miss interaction with earlier changes.'],
  ]);
  add('schemas', 'Structured extraction', [
    ['Which statement about output contracts is accurate?', ['A JSON prompt guarantees all types.', 'Supported strict schema output constrains shape; independent semantic checks still establish correctness.', 'tool_choice alone validates every field.', 'Valid JSON proves the invoice total is correct.'], 1, 'Selection, syntactic structure, and factual validity are separate layers. Even strict schemas cannot prove a value matches the source.'],
    ['A tax ID can be absent, but the schema requires a string. What is the best schema repair?', ['Invent a placeholder ID.', 'Retry until a plausible number appears.', 'Allow null or omission explicitly and define missing-data behavior.', 'Increase temperature.'], 2, 'An honest missing value needs a legal representation. Required-but-nullable and optional have different meanings; choose deliberately.'],
    ['A schema-valid invoice has items 40 and 25 but total 80. What catches the defect?', ['Deterministic arithmetic and source validation.', 'A JSON parser alone.', 'Renaming total to amount.', 'A more compact JSON representation.'], 0, 'The object shape is valid but the data is inconsistent. Semantic checks should compute rather than simply trust a model-generated self-check.'],
  ]);
  add('validation-retry', 'Structured extraction', [
    ['What should a targeted extraction retry include?', ['Only "be careful".', 'Only the failed field name.', 'A new unrelated source document.', 'Original source, failed extraction, and specific validation errors.'], 3, 'The model needs what it read, what it produced, and exactly what failed to correct the relevant mistake.'],
    ['A required fact truly is not in the provided document. What is a sound response?', ['Retry forever.', 'Return a permitted missing value, retrieve approved evidence, or escalate/clarify.', 'Disable validation permanently.', 'Fabricate a well-formed value.'], 1, 'No retry creates missing evidence. Recovery should be honest and bounded.'],
  ]);
  add('batches', 'Continuous integration', [
    ['Which job best fits a 24-hour-tolerant asynchronous batch?', ['An interactive live troubleshooting response.', 'A merge check needed in two minutes.', 'A large archival classification backfill with flexible timing.', 'An approval that must happen before the current purchase.'], 2, 'The backfill has the latency tolerance to benefit from batch economics. Verify the actual deadline and handle per-request expiry or failures.'],
    ['A batch has 980 successes and 20 failures. What next?', ['Match by custom_id, repair the causes, and resubmit only failed requests as appropriate.', 'Resubmit all 1,000 unmodified.', 'Discard the failures silently.', 'Assume the twentieth result belongs to the twentieth input.'], 0, 'Correlate explicitly and avoid paying again for successful work. Oversized inputs need modification before retry.'],
  ]);
  add('context', 'Long-running support', [
    ['Summaries keep losing exact refund amounts. Which change addresses the cause?', ['Longer final answers.', 'A larger font in the prompt.', 'More vague summaries.', 'A structured case-facts block preserving exact amounts and identifiers outside lossy summaries.'], 3, 'Precision-critical state should survive independently of narrative compression. Increasing output budget does not restore discarded facts.'],
    ['Choose TWO ways to protect context during a large codebase investigation.', ['Read every file into the main session.', 'Keep verified key findings in a scratchpad.', 'Ask the model to forget previous tool output.', 'Double max_tokens indefinitely.', 'Delegate focused verbose research and return concise evidence-based summaries.'], [1, 4], 'A scratchpad preserves findings, while isolated research keeps bulk out of the primary conversation. Neither should preserve stale unverified facts as current.'],
  ]);
  add('provenance', 'Research team', [
    ['Two credible sources give different figures for the same-sounding metric. What should a specialist return?', ['Only the larger number.', 'Their average without attribution.', 'Both figures with sources, dates, definitions, and an explicit conflict note.', 'Neither source because disagreement proves both are false.'], 2, 'Preserve evidence for deliberate reconciliation. The figures may concern different periods or populations; silent selection loses that information.'],
    ['Citations disappear during synthesis. What structural change helps?', ['Carry claim-evidence-source-date records through every handoff.', 'Invent plausible links at the end.', 'Write "sources available" without retaining them.', 'Use more confident prose.'], 0, 'Provenance must survive the pipeline. A later writer cannot reliably reconstruct discarded source mappings.'],
  ]);
  add('escalation', 'Customer support', [
    ['A customer explicitly asks for a human before troubleshooting. What should the agent do?', ['Try one more diagnostic anyway.', 'Run a sentiment classifier first.', 'Ask three optional intake questions before routing.', 'Honor the handoff request without first forcing autonomous resolution.'], 3, 'The explicit preference is the trigger. Do not replace it with a guess about emotion or solvability.'],
    ['What belongs in a handoff when the human lacks the transcript?', ['Only a sentiment score.', 'Verified identity, issue, key facts, attempts, blockers, and next-step recommendation.', 'Every raw payload with no summary.', 'Only the final apology.'], 1, 'A self-contained case summary preserves useful work. Avoid invented root causes or unnecessary sensitive data.'],
  ]);
  add('calibration', 'Structured extraction', [
    ['Aggregate extraction accuracy is 97%. What must be checked before reducing human review?', ['Only the overall average.', 'Whether output is grammatical.', 'Per-document-type and per-field accuracy, with calibrated thresholds and ongoing sampling.', 'Whether the model likes the new policy.'], 2, 'Small poor-performing segments can disappear in the aggregate. Calibration and stratified audits keep automation accountable.'],
    ['Choose TWO sound confidence-based review practices.', ['Calibrate field-level thresholds against labeled data.', 'Trust any self-score above 0.9 automatically.', 'Stop measuring after rollout.', 'Route ambiguous sources and low calibrated confidence to review.', 'Sample only the first submissions of each day.'], [0, 3], 'Calibration makes the signal empirical, and routing combines measured uncertainty with source ambiguity. Continue sampling high-confidence cases too.'],
  ]);
  add('retrieval', 'Production architecture', [
    ['An exact part ID retrieves similar but wrong parts using vector search. Which fix best preserves natural-language search too?', ['Replace all retrieval with substring matching.', 'Tell users not to use IDs.', 'Increase output tokens.', 'Hybrid exact/keyword and semantic retrieval matched to query type.'], 3, 'Exact identifiers need lexical precision; natural language benefits from semantics. Combining them avoids sacrificing either workflow.'],
    ['Contract chunks split clauses away from their definitions. What is most direct?', ['Smaller arbitrary chunks.', 'Structure-aware chunks with links to definitions and cross-references.', 'Remove all headings.', 'Ask the model to infer missing definitions.'], 1, 'Preserving document structure and linkable context addresses the retrieval defect before generation.'],
    ['Daily source updates leave superseded answers in retrieval. Choose TWO fixes.', ['Ignore version metadata.', 'Only lower temperature.', 'Validate refresh/re-index completeness and consistency.', 'Add explicit document versions and exclude superseded content for current queries.', 'Increase the response length.'], [2, 3], 'Both indexing freshness and query-time version selection matter. Sampling or prompt changes alone do not repair stale retrieval.'],
  ]);
  add('caching', 'Production optimization', [
    ['A request prepends a unique timestamp before 12,000 static tokens. Why are downstream cache hits poor?', ['The changing prefix prevents an exact prefix match.', 'Twelve thousand tokens is always too much.', 'Temperature is not zero.', 'Caching is permanent and therefore already finished.'], 0, 'Cache reuse depends on stable preceding content. Put varying request data after the reusable prefix and verify the usage counters.'],
    ['Choose TWO accurate prompt-caching statements.', ['It makes generated answers deterministic.', 'Reads can be substantially cheaper than uncached input.', 'It discounts all output tokens.', 'Entries never expire.', 'Writes can cost a premium that reuse amortizes.'], [1, 4], 'Caching changes input-processing economics. It is neither a permanent memory store nor an output-determinism feature.'],
  ]);
  add('models', 'Production optimization', [
    ['A simple classification task meets its quality target on several model tiers. Which choice is defensible?', ['Always choose the most expensive.', 'Randomize tiers.', 'Start with the least costly tier meeting the measured target and continue monitoring.', 'Avoid evaluations because tiers are equivalent.'], 2, 'Choose against task-specific evidence and operating constraints. Larger capability is not automatically worth its cost for a simple task.'],
    ['Does temperature 0 guarantee byte-identical responses?', ['No; design for variation and validate outputs.', 'Yes for every model.', 'Yes if streaming is off.', 'Yes if max_tokens is fixed.'], 0, 'Lower sampling randomness is not a platform guarantee of exact determinism. Use deterministic code where byte identity is mandatory.'],
    ['What distinguishes supported fast mode from reasoning effort?', ['They are the same setting.', 'Fast mode removes the need for reasoning.', 'Effort changes only network speed.', 'Fast mode prioritizes generation speed; effort guides reasoning allocation, with model-specific support.'], 3, 'These are different dimensions with different pricing and quality implications. Do not infer current availability or exact pricing from an old practice answer.'],
  ]);
  add('latency', 'Application integration', [
    ['Users see nothing until a long, otherwise useful answer completes. What most directly improves perceived waiting?', ['Truncate every answer.', 'Stream the response as it is generated, with appropriate presentation safeguards.', 'Send the request to batch.', 'Increase randomness.'], 1, 'Streaming makes progress visible without necessarily changing total generation time. It is not inherently a token discount.'],
    ['Hundreds of independent summaries are needed in minutes. Which execution approach fits?', ['One serial loop.', 'One giant combined document.', 'Bounded async concurrency respecting service and account limits.', 'A 24-hour batch regardless of the deadline.'], 2, 'Independent work can overlap. Bound concurrency and account for token as well as request limits.'],
    ['How should a remote vision request receive an uploaded receipt?', ['Supported image content blocks plus the extraction instruction.', 'Only a local filesystem path string.', 'A promise that the image exists.', 'A required external OCR step for every model.'], 0, 'The remote API needs actual supported image input. A local pathname is just text unless your application reads and sends the file.'],
  ]);
  add('resilience', 'Application integration', [
    ['An app instantly retries every 429 in a tight loop. What is the correct replacement?', ['No retries of any kind.', 'Switch models on every 429.', 'Change the temperature.', 'Use configured SDK retries, server retry guidance, bounded backoff with jitter, and queuing where needed.'], 3, 'Disciplined recovery reduces synchronized pressure. Avoid multiplying retry loops across SDK and application layers.'],
    ['A payment request timed out. What must be considered before retrying?', ['The response font.', 'Whether the first request may have succeeded and how idempotency prevents duplication.', 'Whether a more polite prompt would help.', 'Only the size of max_tokens.'], 1, 'A timeout does not establish that no side effect occurred. Check status and use an idempotent operation design.'],
  ]);
  add('evaluations', 'Production quality', [
    ['A team has only positive demo anecdotes. What belongs before a launch decision?', ['A general benchmark leaderboard.', 'A larger model without testing.', 'Task-specific metrics, representative tests, and agreed launch thresholds.', 'A declaration that all users will adapt.'], 2, 'Readiness must be defined against the actual product and risk. Demos are useful discovery, not a sufficient release gate.'],
    ['Which dataset provides the strongest pre-production signal?', ['Representative appropriately de-identified real inputs plus targeted edge and adversarial cases.', 'Only prompt examples.', 'Only easy questions generated from documentation.', 'Only inputs from the engineers who built it.'], 0, 'Representative inputs capture normal use; designed hard cases probe limits. Keep evaluation distinct from prompt demonstrations.'],
    ['Tone must be evaluated at high volume. Which method is appropriate?', ['Exact matching against one approved paragraph.', 'No evaluation because tone is subjective.', 'Trust every model self-score.', 'A rubric-based LLM judge periodically calibrated against human expert ratings.'], 3, 'A calibrated judge can scale subjective review. Its agreement and failure patterns still require measurement.'],
  ]);
  add('security', 'Production safety', [
    ['An incoming email contains instructions to forward private data externally. Choose TWO controls.', ['Only repeat a prompt warning.', 'Treat message content as untrusted data separate from trusted instructions.', 'Give the model administrator credentials.', 'Use least-privilege tools and enforced approval for sensitive actions.', 'Block only the literal word ignore.'], [1, 3], 'Trust separation reduces susceptibility, while enforced capability limits and approval reduce consequences. Neither prompt wording nor a keyword blocklist is enough.'],
    ['A public JavaScript bundle contains an API key. What is required?', ['Obfuscate the variable.', 'Keep the key but lower its limit.', 'Rotate the exposed key and move calls behind a backend using approved secret storage.', 'Ask visitors not to use it.'], 2, 'Anything delivered to a browser is extractable. Rotation addresses the compromise; moving the secret fixes the architecture.'],
    ['How should dev, staging, and production credentials be arranged?', ['Distinct, appropriately scoped keys with rotation and revocation.', 'One shared key to simplify compromise.', 'A production key committed in settings.', 'Randomly rename the same key variable.'], 0, 'Environment separation limits the reach of compromise and makes management auditable. Storage alone does not create isolation.'],
  ]);
  add('discovery', 'Solution design', [
    ['Which is an infrastructure requirement?', ['Reduce support cost by 20%.', 'Draft replies to tickets.', 'Use a friendly tone.', 'Autoscale to 500 concurrent requests while meeting the latency target.'], 3, 'Capacity and scaling describe platform characteristics derived from business and quality goals. Drafting is a function, not infrastructure.'],
    ['Choose TWO non-functional requirements.', ['Create a CRM task after escalation.', 'p95 response time below three seconds.', 'Never expose another customer\'s data.', 'Draft a message for every ticket.', 'Grow the business by 20%.'], [1, 2], 'Performance and data isolation constrain system quality. The other statements describe functions or a business objective.'],
    ['Which pilot sequence is most defensible?', ['Scale, then measure.', 'Choose the highest-risk process and skip baseline.', 'Map and baseline, select a low-risk bottleneck, pilot, evaluate, then scale.', 'Prototype a solution before learning the problem.'], 2, 'A baseline and pre-agreed criteria make the pilot interpretable. Scale follows evidence, not excitement.'],
  ]);
  add('observability', 'Production quality', [
    ['Wrong answers might come from bad retrieval or misread evidence. What comes first?', ['Inspect failing traces: input, retrieved context, tool results, and output.', 'Rewrite the prompt immediately.', 'Upgrade the model automatically.', 'Add only a disclaimer.'], 0, 'Different failure locations require different fixes. Trace evidence prevents blind changes that destabilize working behavior.'],
    ['At high scale, what is a sound observability design?', ['Record nothing.', 'Only final answers without correlation.', 'Export all secrets in every payload.', 'Structured correlated traces and metrics, with redacted full payloads sampled or captured on relevant failures.'], 3, 'Broad structured visibility plus selective detail makes failures findable while controlling cost and exposure.'],
  ]);
  add('governance', 'Responsible use', [
    ['Before uploading employee data, choose TWO necessary checks.', ['Whether its colors look good.', 'Its sensitive categories and required minimization or special handling.', 'Whether it has enough rows to impress.', 'Whether the approved tool, purpose, and workspace are permitted by policy.', 'Whether a prompt promises confidentiality.'], [1, 3], 'Inspect the data and the permitted use. De-identification may reduce risk but does not automatically satisfy all obligations.'],
    ['A health-data project wants to start now and obtain agreements later. What is appropriate?', ['Proceed with a small real sample.', 'Delete the chats afterward.', 'Resolve applicable obligations and the entire data path before processing regulated records.', 'Only encrypt the final answer.'], 2, 'Contracts, approved services, retention, and subprocessors shape the architecture before data flows. Small unauthorized processing is still processing.'],
    ['Removing names does not eliminate a hiring-score disparity by postcode. What should happen?', ['Evaluate proxy bias across relevant groups, remediate, and keep monitoring with qualified oversight.', 'Assume fairness because names are gone.', 'Hide the scores.', 'Conclude the application has no available controls.'], 0, 'Proxy variables can carry sensitive correlations. Evaluate observed behavior rather than relying only on excluded columns.'],
    ['Confidential documents were pasted into an unapproved personal AI account. What next?', ['Ignore it because the model is similar.', 'Delete evidence and say nothing.', 'Continue using that account.', 'Follow the exposure-reporting process and redirect work to the sanctioned environment.'], 3, 'Governance depends on workspace terms and controls, not just model capability. Report and contain the exposure through the approved process.'],
    ['Does pseudonymization alone settle every international data-transfer issue?', ['Yes, always.', 'No; data can remain personal and lawful transfer, purpose, access, and contractual requirements still matter.', 'Yes if the prompt uses the word private.', 'Only the model parameter count matters.'], 1, 'Minimization is one control in a larger privacy design. Qualified privacy review must cover the actual data flow.'],
  ]);
  add('lifecycle', 'Solution lifecycle', [
    ['A live application now needs issue response, monitoring, and deliberate upgrades. Which phase is this?', ['Retirement.', 'Only original requirements gathering.', 'Operations and maintenance.', 'No further phase after shipping.'], 2, 'Production ownership continues through monitoring, defect response, and evolution. Launch is not the end of the lifecycle.'],
    ['What handoff best equips the receiving engineering team?', ['Decision records, operational runbooks, and re-runnable evaluation baselines alongside the code.', 'Only a final demo recording.', 'Every abandoned prompt draft but no runbook.', 'Only the feature backlog.'], 0, 'The team must understand, operate, recover, and safely change the system. A demonstration alone does not transfer that capability.'],
    ['Does running your agent in your own cloud automatically prove inference residency?', ['Yes, for every provider.', 'Only if the frontend is local.', 'Yes if the prompt says the region.', 'No; inspect model inference, retrieval, logs, storage, subprocessors, and agreements.'], 3, 'The agent runtime is only one part of the data path. Establish compliance before selecting or launching the deployment.'],
  ]);
  add('releases', 'Production quality', [
    ['A new model improves reasoning but breaks 3% of structured results. What next?', ['Upgrade immediately based on the average benefit.', 'Adapt the integration and prompts, re-evaluate all acceptance criteria, then roll out gradually if they are met.', 'Stay on the old model forever.', 'Silently drop malformed outputs.'], 1, 'Correctness regressions are not canceled by unrelated benchmark gains. Fix and validate the integration before controlled migration.'],
    ['A plugin update regressed behavior and nobody recorded the prior version. What practice prevents this?', ['Stop all third-party use permanently.', 'Always use latest without history.', 'Version, pin, review, and deliberately update plugin dependencies.', 'Ask the model to remember a version it never saw.'], 2, 'Configuration history supports reproducibility and rollback. Keeping every version implicit removes the evidence needed to recover.'],
  ]);
  add('stakeholders', 'Solution lifecycle', [
    ['A sponsor requests 100% LLM accuracy. What is the professional response?', ['Explain probabilistic behavior and agree measurable acceptance criteria plus risk-appropriate error handling.', 'Promise it after enough testing.', 'Use a cheaper model as a guarantee.', 'Hide errors in reports.'], 0, 'Translate an absolute into a testable agreement without misrepresenting limitations. High-risk outcomes may require deterministic constraints or human review.'],
    ['Stakeholders keep adding material scope during the build. Choose TWO sound practices.', ['Absorb it invisibly.', 'Reduce testing secretly.', 'Assess each request against success criteria and make its impact visible.', 'Refuse all discussion.', 'Re-baseline timeline, cost, and risk with accountable sign-off when needed.'], [2, 4], 'Transparent impact assessment and explicit change approval preserve both delivery integrity and the working relationship.'],
    ['Leadership reports include only token cost and uptime. What should lead instead?', ['More technical counters.', 'Measured business outcomes agreed at discovery, with technical evidence and honest limitations.', 'Only a list of new model names.', 'An unsupported claim of perfection.'], 1, 'Stakeholders funded outcomes such as time saved and fewer errors. Technical metrics support, but do not replace, that story.'],
  ]);
  add('prompt-debugging', 'Prompt workshop', [
    ['Every new Project conversation uses the wrong tone. Where should you fix it?', ['In each chat forever.', 'By increasing the context window.', 'In the shared Project instructions, followed by testing.', 'By changing the clock time of requests.'], 2, 'A repeatable configuration-level defect should be fixed at its shared source. Validate the updated behavior rather than promising perfect compliance.'],
    ['Choose TWO practices for reliable prompt improvement.', ['Change one meaningful variable at a time.', 'Rewrite everything on every attempt.', 'Switch products before diagnosing.', 'Compare on the same stable test set.', 'Judge only the most flattering output.'], [0, 3], 'Controlled changes and consistent evaluation preserve attribution. A broader representative set avoids tuning to one lucky example.'],
  ]);
  add('frameworks', 'Architecture desk', [
    ['What do agent frameworks primarily supply?', ['Guaranteed correctness.', 'Automatic fine-tuning for every prompt.', 'Freedom from testing.', 'Reusable model invocation, state, tool-loop, and orchestration abstractions.'], 3, 'Frameworks reduce engineering plumbing. Policy, application evaluation, deployment, and operational responsibility remain.'],
    ['A small team prefers managed hosting, but customer data has strict regional obligations. What controls the choice?', ['Shipping speed alone.', 'Verified compliance of the full data path, then operational trade-offs among permitted options.', 'Whether the word managed appears.', 'A promise to review compliance after launch.'], 1, 'Choose within non-negotiable constraints before optimizing delivery speed. Managed hosting can fit if the actual contract and architecture satisfy them.'],
  ]);
  add('responsible-writing', 'Everyday work', [
    ['A draft is legally consequential but reads well. What determines the next step?', ['Its length.', 'The model\'s confidence.', 'Qualified legal review before relying on it.', 'A grammar check alone.'], 2, 'The stakes and required expertise determine review, not fluency. AI can assist preparation without substituting for the accountable professional.'],
    ['A request asks for invented customer testimonials presented as real. What is appropriate?', ['Decline the deceptive presentation and offer genuine feedback collection or clearly labeled fictional examples.', 'Publish them under first names only.', 'Add a nearly invisible disclaimer.', 'Treat all polished marketing as equally fictional.'], 0, 'Do not manufacture social proof. Legitimate alternatives meet the communication goal without misrepresenting evidence.'],
    ['A job ad uses age-coded language unrelated to the role. What should the author do?', ['Publish because generated language is neutral.', 'Add a disclaimer but leave the substance.', 'Make it more exciting.', 'Replace it with relevant skill and competency language and review for bias.'], 3, 'Fix the substantive criteria. A neutrality claim or disclaimer does not remove biased framing.'],
    ['An AI-assisted report causes a problem because of an unchecked error. Who owns the work product?', ['Nobody.', 'The responsible author and approval process, not the model as a substitute for accountability.', 'Only the chatbot.', 'Only the person who installed the browser.'], 1, 'AI assistance does not transfer human and organizational accountability. Review is part of the work, not an optional afterthought.'],
  ]);

  const matching = [
    { lesson: 'workflow-choice', domains: { professional: 'design' }, stem: 'Match each task to the simplest suitable architecture.', options: ['Single augmented call', 'Fixed workflow', 'Autonomous agent', 'Multi-agent system'], items: ['Translate supplied text with a glossary.', 'Run the same five approved processing stages.', 'Investigate an outage whose next query depends on findings.', 'Coordinate independent legal, technical, and financial specialists.'], correct: [0, 1, 2, 3], rationale: 'Match structure to uncertainty and specialization. Translation is one transformation; a stable sequence is a workflow; investigation needs adaptive action; separate specialist contexts can justify a team.' },
    { lesson: 'mcp', domains: { professional: 'integration' }, stem: 'Match the integration need to its primary mechanism.', options: ['MCP server', 'Direct API integration', 'Agent-to-agent protocol'], items: ['Several AI clients reuse a centrally maintained ticketing capability.', 'A deterministic job transfers records with no model decisions.', 'Agents operated by different firms coordinate through an agreed boundary.', 'One owned service invokes a model once for classification.'], correct: [0, 1, 2, 1], rationale: 'MCP supports reusable AI-facing capabilities; direct APIs fit owned deterministic connections; agent-to-agent communication connects independently operated agents without granting each other internal access.' },
    { lesson: 'governance', domains: { professional: 'governance' }, stem: 'Match the risk to the most direct primary control.', options: ['Preventative guardrail', 'Human approval', 'Monitoring and audit'], items: ['Prevent account numbers from reaching the display.', 'Approve a consequential financial recommendation.', 'Reconstruct a disputed action months later.', 'Detect rising error rates across the service.'], correct: [0, 1, 2, 2], rationale: 'Block disallowed output before display; review consequential decisions before execution; retain auditable records and metrics for reconstruction and trend detection. These controls complement one another.' },
    { lesson: 'lifecycle', domains: { professional: 'lifecycle' }, stem: 'Match each activity to the lifecycle phase it primarily belongs to.', options: ['Discovery', 'Design', 'Handoff', 'Monitoring and iteration'], items: ['Agree success measures with frontline users.', 'Select retrieval and approval architecture.', 'Walk the new owners through recovery runbooks.', 'Use production errors to prioritize improvements.'], correct: [0, 1, 2, 3], rationale: 'Discovery establishes the goal and constraints; design selects the system; handoff transfers ownership; ongoing evidence drives improvement after launch.' },
  ];
  matching.forEach((question) => bank.push({ ...question, id: `atlas-${bank.length + 1}`, kind: 'matching', scenario: 'Architecture matching', source: 'Atlas original practice' }));
  bank.push(...scenarios.flatMap((scenario) => scenario.questions));
  return bank;
});